### ISSUE TITLE
Out-of-the-box zigbee2mqtt support

### ISSUE THREAD

**Issue by Koenkk** [mattlokes/zwallremote#1]
Hi!

I just saw this nice project, I want to mention that it can be supported out-of-the-box by zigbee2mqtt in case you want to. Just make a PR against zigbee-shepherd-converters and I will merge it.

**Comment by mattlokes** [comment]
Sure that would be cool, i have been meaning to send you a PR so i dont have to keep merging my changes.

**Comment by mattlokes** [comment]
Done, pull requests:

https://github.com/Koenkk/zigbee-shepherd-converters/pull/665
https://github.com/Koenkk/zigbee2mqtt/pull/2076

Thanks
Matt
