### ISSUE TITLE
Tradfri

### ISSUE THREAD

**Issue by arcidodo** [mattlokes/zwallremote#2]
can you control an ikea tradfri bulp directly or do you need to go trough the server? (zigbee2mqtt)

i want to make my wall switches smart to control the light directly so it still works if the server is offline.

**Comment by mattlokes** [comment]
If you set the address, to the bulb you wish to control, instead of the
coordinator. Using the instructions in the README.

It will work just fine, since the switch just sends the TOGGLE Zigbee Light
Link command.

Thanks
Matt

**Comment by arcidodo** [comment]
nice thanks!
